gcc policyWatcher.c parse.c cJSON.c utility.c -I /usr/local/include/zookeeper/ -I /usr/include/libxml2/ /usr/local/lib/libzookeeper_mt.so /usr/lib64/libxml2.so -lm -w -o aa
#gcc policyWatcher.c -I /usr/local/include/zookeeper/ /usr/include/libxml2/libxml/ /usr/local/lib/libzookeeper_mt.so  cJSON.c utility.c parse.c -lm -g -w -o  policyWatcher
